### ISSUE TITLE
Mob and Meat ores should reference loot tables?

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/FunOres#13]
Had this suggestion a while back. Honestly, configuring drops for these ores is a bit of a pain, and beyond what most people are willing to do. If the ores can just use the loot tables of there respective mob, that would be great (good for mod compatibility too).

A method to custom configure ore drops should still be left in place however. It could be useful in some cases. Also might be good to have multiple config files, in a folder dedicated to Fun Ores.

**Comment by jriwanek** [comment]
Take a look at Additional loot tables, I'm not sure if it works for mobs (yet), but it may cover your needs, and if it doesn't we can improve it.
