### ISSUE TITLE
Crash on forge server (1.10.2 12.18.1.2039)

### ISSUE THREAD

**Issue by drakray** [SilentChaos512/FunOres#14]
I got this crash when trying to start a server with FunOres (1.3.0-71) in it:

http://pastebin.com/1jjphLT3

Work nice on my clients though.

**Comment by SilentChaos512** [comment]
OK, looks like a simple enough fix.
(edit) Not as simple as I thought, but not hard.

**Comment by SilentChaos512** [comment]
Look for version "1.3.0-73 (server hotfix)" on Curse in a bit. Clients should not need to update, but can.
