### ISSUE TITLE
[Suggestion] Make a config option to make 1 ingot = 1 plate to be in line with other mods

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/FunOres#17]
For example, in TiCo, you only need 144mb (1 ingot) to make a plate.

**Comment by SilentChaos512** [comment]
Fair enough... My long-term plans for the mod fell apart anyway. Well, that might not be the best way to word it. The idea was that plates should be a greater cost than ingots for recipe balance. But I'll add the config option.
