### ISSUE TITLE
1.11 version not working

### ISSUE THREAD

**Issue by Majestyc2k1** [SilentChaos512/FunOres#19]
I installed Fun Ores 1.11 (1.11-1.3.4-81) through the Curse launcher, but the mod is not loading in game. Nothing in JEI, its not on the mod list, nor is a config file being generated. I also have SilentLib 1.11-1.1.3-28 and Forge 13.19.1.2189.

**Comment by SilentChaos512** [comment]
Seems like it's not being detected as a mod for whatever reason. I can see there are some errors showing up because of recent Forge changes. Normally that would just crash the game though, so I'm not sure if that's the problem. I'll start by fixing those first chance I get.

**Comment by SilentChaos512** [comment]
Should be fixed in version 1.4.0.
