### ISSUE TITLE
Ores not generating in other dimensions

### ISSUE THREAD

**Issue by Thiana** [SilentChaos512/FunOres#2]
Dimensions created with the SimpleDimensions mod are not generating any funores. Thaumcraft/Deep Resonance/ResourcefulCrops/Dense Ores all generate correctly. Funores do generate correctly in the overworld/nether.

I'm not sure if this is limited to SD's dimensions only since I have no other mods to create extra dimensions.

I've checked the funores config but I don't see anything regarding dimension blacklisting/whitelisting.

I'm not sure if it makes a difference, but the dimension ids for SD dims are all 30000+

Versions:
SimpleDimensions 1.8.9-0.0.4
FunOres 1.8.9-1.1.2-54
Forge 1764

Thanks.

**Comment by SilentChaos512** [comment]
Looks like a small oversight on my part. Should be an easy fix.
