### ISSUE TITLE
Favors MOUNTAIN perhaps not working

### ISSUE THREAD

**Issue by Zygus42** [SilentChaos512/FunOres#20]
vFunOres-1.10.2-1.3.3-79, forge-1.10.2-12.18.3.2185
I set up our local server so that certain ores would spawn a lot more in some biome types than others, and most of them seem fine, and I can't be 100% certain, but it is beginning to look like anything with Favors MOUNTAIN is not spawning as intended, as in there's essentially none where there's meant to be lots.  Now, I used MOUNTAIN as the key word because that's what base Minecraft uses.  It isn't by any chance MOUNTAINS in your mod ?  or something equally simple ?

**Comment by SilentChaos512** [comment]
Send me your config file and I'll take a look at it when I get a chance.

**Comment by Zygus42** [comment]
[FunOres.zip](https://github.com/SilentChaos512/FunOres/files/708966/FunOres.zip)

**Comment by SilentChaos512** [comment]
Something's definitely wrong with the mod. I'm testing on 1.11, but I'm seeing copper avoid a mountain biome with your config. I'll see what I can do.

**Comment by SilentChaos512** [comment]
OK, so this is partially a code problem, partially config. For some reason, I changed the name of the list from "BiomeTypes" to "Biomes", so you need to move your lists to "Biomes". I think I did that when I was adding the ability to list specific biomes. I can remove the old list at least. There also should not be commas in the list, that's something I can also add a check for. And finally I'm not checking names right. I'll have that fixed for next version.
