### ISSUE TITLE
Crash when loading minecraft

### ISSUE THREAD

**Issue by sayblekitten** [SilentChaos512/FunOres#26]
MC 1.11.2 Forge 13.20.0.2225
Mods: Funores, SilentLib

When disabling passive mob and/or hostile mob ores and launching the instance, the instance crashes the game before it reaches the splash page. Crash log attached.

[crash-2017-01-31_16.37.43-client.txt](https://github.com/SilentChaos512/FunOres/files/743427/crash-2017-01-31_16.37.43-client.txt)

**Comment by SilentChaos512** [comment]
Looks like the crash is caused by not having JEI installed. Should be easy enough to fix.

**Comment by sayblekitten** [comment]
Nicely done, thanks for handling that so quick.
