### ISSUE TITLE
Config and ore spawning issues

### ISSUE THREAD

**Issue by Zygus42** [SilentChaos512/FunOres#27]
1.10.2 - versions FunOres-1.11.x-1.5.1-101 & FunOres-SilentLib-1.10.2-2.0.2-42

This is the config I've ended up with:
[funores.txt](https://github.com/SilentChaos512/FunOres/files/833015/funores.txt)

Something is not working correctly with the FAVORS option - maybe it's multiplying in the favored places, but not dividing in the unfavored places ?  Not sure exactly, only that I'm not getting the result I'm after, which is a tiny amount of ores in most places, and large deposits in others by biome type.

-------------------

Also a few minor issues in the config in the recipe_extra section, with there being double-ups of recipes for aluminium items, and those doubled up recipes are showing twice in JEI.

---------------------

Also, if you try and go to the second set of tabs in JEI (the non-vanilla minecraft ones) in creative mode, which should at this point only have the fun ores tab, it crashes with:
[crash-2017-03-10_13.09.30-client.txt](https://github.com/SilentChaos512/FunOres/files/833022/crash-2017-03-10_13.09.30-client.txt)

**Comment by SilentChaos512** [comment]
Is it only vanilla ores that seem to be affected? It looks like the configs for vanilla ores aren't loading correctly, as the ReplaceExisting option isn't there (you'll want to enable that when I get it fixed). Biome lists are working correctly in the latest version, as far as I can tell, so my guess is you are seeing vanilla oregen.

One way you can test whether FAVORS is working or not is using WIT's advanced mode. It reports the number of veins that _should_ try to spawn in each chunk for the biome. Install WIT, press numpad 4 to toggle advanced mode, place the ore in the biome you are testing, and look at it. It also lists the types of the current biome. Just make sure you are at least 1-2 chunks into the biome, or it might display the wrong biome (it goes by the biome at the center of the chunk, if memory serves).

Aluminium recipe configs are working as intended. I included one for both spellings (aluminium (extra i) and aluminum). Some mods only oredict their ingots to one spelling, so I'm just being thorough.

I'll take a look at the creative tab crash later today. Probably a cross compat issue.
(edit) Oh, JEI tabs. Must learn to read. But the crash still doesn't happen for me in either 1.10.2 or 1.11.

**Comment by Zygus42** [comment]
Vanilla vs non-vanilla !  That was exactly the problem.  When I went back to the config, it had replaced all the vanilla ore fields with blank ones, and including the B:ReplaceExisting line this time.  Not sure what went wrong there.  I plugged in my values, ran it again and it looked fine - and it didn't replace the config again, so it's all good.

I can't believe how often I looked at those Aluminum fields and didn't see the different spelling :)  Just goes to show that we see what we expect to see.

It definitely still crashes in your inventory when you change tabs.   To test the inventory problem further, I removed FunOres and added another mod and it's tab showed up fine.  I removed JEI and launched with absolutely nothing but FunOre and SilentLib, and it's still crashing.   I'm using forge 1.10.2-12.18.3.2254 if that makes any difference, but I rolled it back to 1.10.2-12.18.3.2185 and it still crashes.

**Comment by Zygus42** [comment]
Sorry to have to add even more :)  But, I tested some more and it was all good until I got to a Roofed Forest biome.  This ought to be considered Forest & Magical biome types, but it appeared to have favoured everything, in particular it looked like it double-favoured Coal, as the biome was almost solid coal - never seen so much in one place before.

This is the config I'm using:
[funores.txt](https://github.com/SilentChaos512/FunOres/files/835560/funores.txt)

I'm testing on Seed 277249098916529181, vanilla minecraft (with forge, FunOres, SilentLib & WorldStripper, nothing else), and in creative.  You start in a Taiga, there's a Plain nearby and a Roofed Forest just past that.

**Comment by SilentChaos512** [comment]
Replicated the crash, it is a creative tab issue. I forgot to switch it to the compat version. Not sure why I couldn't get it to happen before.

I took a look at the roofed forest on that seed (with the config you provided) and didn't see anything out of place. I also have Gems installed, but here's a screenshot:
![2017-03-11_12 05 58](https://cloud.githubusercontent.com/assets/5721949/23825793/123a65f4-0656-11e7-8944-dd11910cd423.png)
Seems to be mostly copper and coal, as I would expect. WIT reports 80 copper veins in that biome, although it doesn't report for coal at the moment.

**Comment by Zygus42** [comment]
This is the pic from a Roofed Forest:
![2017-03-12_04 31 18](https://cloud.githubusercontent.com/assets/20757445/23826702/f6e038b0-06dc-11e7-9377-5dc6f7d9568f.png)

and this is from a Taiga:
![2017-03-12_04 31 54](https://cloud.githubusercontent.com/assets/20757445/23826705/0d07e4f8-06dd-11e7-8684-2a497f35e28f.png)

Both count as forests, but there's a ton more (twice as much ??)  coal in the Roofed Forest, and coal is set to:
        S:BiomeListType=FAVORS
        S:Biomes <
		FOREST
		JUNGLE
         >

I think a Roofed Forest is:
 registerBiomeType(roofedForest,        SPOOKY,   DENSE,      FOREST                 );

**Comment by Zygus42** [comment]
Using newest versions(FunOres-1.11.x-1.5.2-104 & SilentLib-1.10.2-2.0.3-43), no longer get crash with inventory, but same results for odd spawning as above in Roofed Forest & Taiga.  

Also checked Plains, and this seems as specified (I think):
![2017-03-13_00 29 01](https://cloud.githubusercontent.com/assets/20757445/23833832/8b86a9c8-0786-11e7-8f39-5d46beabc7b0.png)

But Swampland is not even close, with lots of coal and iron, neither one of which is meant to favor swamp:
![2017-03-13_00 28 30](https://cloud.githubusercontent.com/assets/20757445/23833837/9e537f40-0786-11e7-9523-628d339e57f3.png)

I used WIT in advanced mode, but it only seems to work on non-vanilla ores, so on coal, iron etc, it doesn't give the spawn info, and it looks like the vanilla ores are the main problem here.

Is it possible that maybe the normal vanilla ores are not all being removed ?  Although that wouldn't explain the Plains.

**Comment by SilentChaos512** [comment]
Uploading 1.5.2b, let me know if there are still any issues.

**Comment by Zygus42** [comment]
It works !  Excellent work and thanks for all the effort.
