### ISSUE TITLE
Crash using FunOres-1.11.x-1.5.2b-106

### ISSUE THREAD

**Issue by drakray** [SilentChaos512/FunOres#28]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fun Ores (funores)
Caused by: java.lang.NoClassDefFoundError: net/silentchaos512/funores/block/machine/BlockMetalFurnace

http://pastebin.com/bYg91mdJ

Minecraft 1.11.2
Forge 2255
list of mods in file

UCE on JEI and JER too, if that may help

EDIT: -104 load without crash

**Comment by Zarepheth** [comment]
I'm receiving the same error on the same version of FunOres.

Minecraft 1.11.2
Forge 2255

A long list of mods, though JEI also erred for me when dealing with some FunOres machines while the game was loading. Anyway, if a second crash report helps the trouble-shooting, here it is.

[crash-2017-03-12_17.47.16-client.txt](https://github.com/SilentChaos512/FunOres/files/836967/crash-2017-03-12_17.47.16-client.txt)

**Comment by SilentChaos512** [comment]
I need a log file as well, if possible.

**Comment by drakray** [comment]
[Crashlog](http://pastebin.com/bB3vHBVk)
[Forgelog](http://pastebin.com/XVbwAi0N)

**Comment by SilentChaos512** [comment]
Still not sure why this is crashing. I can't get it to happen. But I've got a theory and I'm uploading a new build now. Let me know whether it fixes the problem or not.

**Comment by drakray** [comment]
trying live
didn't crash, can say it's fixed in 107
