### ISSUE TITLE
List of possible missing stuff

### ISSUE THREAD

**Issue by jriwanek** [SilentChaos512/FunOres#3]
Block of Charcoal (Likely outside of mod scope, but you don't ask, you don't get)

Rutile
Magnesium

Wood Gear
Obsidian Gear/Plate
Maybe Diamond + Emerald Gears? (Possibly Plates too)

Emerald/Diamond/Enderpearl Shards.

**Comment by SilentChaos512** [comment]
I like several of these ideas, especially the extra vanilla gears/plates/nuggets.

Cobalt and Ardite are an idea of struck down in the past. If they were used by more than TCon, or not found in the Nether, I might. Not sure about most people, but I reset my Nether whenever I need new ores.

Rutile is titanium, isn't it? The mod already has titanium.
What mod uses magnesium? I can't think of any off the top of my head.

**Comment by jriwanek** [comment]
Awesome, glad to be of assistance.

Fair point on TCon.

Rutile is the Raw form of titanium, I found it through mariculture, magnesium would be from the Mariculture mod too.

https://en.wikipedia.org/wiki/Rutile
