### ISSUE TITLE
Crashing my game again, need help.

### ISSUE THREAD

**Issue by TheGooblyGoob** [SilentChaos512/FunOres#31]
[crash-2017-05-17_15.17.24-client.txt](https://github.com/SilentChaos512/FunOres/files/1009018/crash-2017-05-17_15.17.24-client.txt)

**Comment by SilentChaos512** [comment]
Looks like an OptiFine issue. Nothing I can do about it.

**Comment by TheGooblyGoob** [comment]
Thanks, I did a slightly tedious process of pulling all my mods out, updating my forge, and then putting them back in one by one to see which one was the problem child.
