### ISSUE TITLE
Alloy Smelter crash

### ISSUE THREAD

**Issue by Thrawn92** [SilentChaos512/FunOres#36]
Okay, I had just used the alloy smelter to make Invar ingots, and they smelted fine, but when I took them out of the alloy smelter, the game crashed. Also, I noticed that the background for the alloy smelting gui is pink, as if it's a missing texture (which may or may not be related).

I'm playing on 1.10.2 with a few other technical mods that make use of invar, including Thermal Foundation, Mekanism, and Tinker's Construct. The error report is attached below.
[crash-2017-07-22_09.57.17-client.txt](https://github.com/SilentChaos512/FunOres/files/1167427/crash-2017-07-22_09.57.17-client.txt)

**Comment by SilentChaos512** [comment]
Wow, this bug must have been here since 1.11. I know that few people use the Fun Ores machines, but that's a bit sad. Thanks for reporting this, should be an easy fix.

**Comment by Thrawn92** [comment]
Awesome, thanks!
