### ISSUE TITLE
Not detecting silentlib

### ISSUE THREAD

**Issue by YeLmiSoR** [SilentChaos512/FunOres#39]
Well I have silentlib and fun ores installed the right mc version and the right mods versions but I always get the same message that silentlib is missing 

pls halp

**Comment by SilentChaos512** [comment]
If it is looking for "SilentLib", you have a badly outdated version of Fun Ores.
If it is looking for "silentlib", you have a badly outdated version of Silent Lib.

**Comment by accessdenied0** [comment]
I guess I know what happened here, at least in my case:
If you go on curse and download the latest version of FunOres, you get the _"FunOres-universal-1.5.6-116"_.
If you try to run Minecraft with the SilentLib for 1.10.2 or 1.11.x it says it is outdated (which it is). 
You need the beta version _SilentLib-1.10.2-2.2.6-66.jar_ for 1.10.2 or 1.11.x

[BUT it causes issues with the SuperMultiDrills.](https://pastebin.com/5xQ3qYSt)

**Comment by SilentChaos512** [comment]
Ah, right. I need to do one last update for Drills so that mod can die naturally...

**Comment by SilentChaos512** [comment]
Released a new build of Super Multi-Drills that supports Silent Lib 2.2.6 (does not support MC 1.12). Marked latest versions of Silent Lib for all MC versions as "release".
