### ISSUE TITLE
TIC support for new materials

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/FunOres#41]
Can there be a prismarinium and enderium tool material? The prismarinium tool parts can have Aquadinamic and a high durability and enderium can have enderferrence and high attack. Basically prismarinium is an upgraded version of prismarine and enderium is an upgraded version of end stone

**Comment by SilentChaos512** [comment]
I'll look into this sometime. I kind of know how to add TiC materials thanks to Silent's Gems, but it had some minor issues. Also, Fun Ores is a low priority for me right now, so this might take a while.

**Comment by ghost** [comment]
Ok
