### ISSUE TITLE
Dedicated Server Crash - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/FunOres#43]
### Versions
Forge Version: 1.12.2 - 14.23.4.2747
Minecraft Version: 1.12.2
Fun Ores Version: u-FunOres-1.12.2-1.6.0-120-a.jar
Silent Lib Version: u-SilentLib-1.12.2-2.3.15-134-a.jar

### Expected behavior

- No crashing

### Actual behaviour

- Crashing

### Steps to reproduce the problem

1. Add to dedicated server
2. Run Dedicated Server
3. Crash
4. Profit

### Crash Report

https://gist.github.com/P3rf3ctXZer0/b297a91c722396aa52e75ce3dc7ee031

**Comment by SilentChaos512** [comment]
Darn, I was on a good streak of not crashing servers! Thanks for reporting, as always.

**Comment by SilentChaos512** [comment]
New version uploaded and pending approval. Should be available within the hour.
