### ISSUE TITLE
[Bug] Fish ore drop nothing

### ISSUE THREAD

**Issue by drakray** [SilentChaos512/FunOres#45]
### Versions

Minecraft Version: 1.12.2
Fun Ores Version: 1.6.2-123
Silent Lib Version: 3.0.0-144

### Expected behavior

- Fish ore to Drop fishy stuff

### Actual behaviour

- Fish ore drop nothing

### Steps to reproduce the problem

1. Have FunOre, [Aquaculture](https://minecraft.curseforge.com/projects/aquaculture), [HarvestCraft](https://minecraft.curseforge.com/projects/pams-harvestcraft), [Gravestone Extended](https://minecraft.curseforge.com/projects/gravestone-mod-extended), and [more](https://github.com/SilentChaos512/FunOres/files/2306649/modList.txt)
2. Find Fish Ore and Mine it
3. ...
4. Nothing Happen

At first I thought it could only be a bad luck, but I just mined a >10 block vein of fish ore with 0 drop :/

Could it be caused by a recent update from FunOre or SilentLib, or simply because I have WAY too many mods that add fishy stuff? I know Aquaculture and Gravestone must be fished with their own fishing rod, but still.
Cam't remember last time it worked though, lately I avoided mining fish ore because I lacked the storage space XD

**Comment by SilentChaos512** [comment]
Any mod that changes vanilla fishing could affect fish ore. It simulates a
player fishing, if I remember correctly. My guess would be Aquaculture.
I'll have to look into how they handle fishing, there could be some way to
fix it.

**Comment by drakray** [comment]
Don't know if it can be related, but I can't use BaseMetal's not Thermal Foundation's Fishing Rod.
I can use Minecraft's, Aquaculture's and Gravestone-Ext's, though

**Comment by drakray** [comment]
Just so you know, Gravestone-Extended no longer have a fishing module; it's been moved to [Advance Fishing](https://minecraft.curseforge.com/projects/advanced-fishing), but problem still exist.

**Comment by MauveCloud** [comment]
I was able to reproduce this with only FunOres-1.12.2-1.6.2-123.jar and SilentLib-1.12.2-3.0.8-158.jar in the mods folder, and Forge build 2768 (config modified and custom superflat world to find the ores faster, and creative mode to give myself a diamond pickaxe, but then I switched to survival before mining).

Edit: I found why this is happening!
https://github.com/SilentChaos512/FunOres/commit/86334a2ef66d54ea3543fc0ac3b42d43f640e775#diff-1ebc7cb19fba960d411ad0e101bf95dcR52 added an early return if the EntityLiving for the ore type is null, but fish ore (presumably intentionally) returns such a null here: https://github.com/SilentChaos512/FunOres/blob/1.12/src/main/java/net/silentchaos512/funores/lib/EnumMeat.java#L109
