### ISSUE TITLE
Dedi Server Crash

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/FunOres#46]
### Versions

Forge Version: 14.23.4.2759
Minecraft Version: 1.12.2
Fun Ores Version: 1.6.2-123
Silent Lib Version: 3.0.5-152

### Expected behavior

- Server start up continues as normal

### Actual behaviour

- Server crashes during startup with a java.lang.NoClassDefFoundError

### Steps to reproduce the problem

1. Run the server with above mod versions
2. Crash during loading

[crash-2018-09-13_15.28.15-server.txt](https://github.com/SilentChaos512/FunOres/files/2379607/crash-2018-09-13_15.28.15-server.txt)

The error looks like it's missing a dependency, but the only one is SilentLib which is definitely in there.

**Comment by SilentChaos512** [comment]
Silent Lib 3.0.5 fixes this issue (your crash report shows 3.0.4)

**Comment by GamertechAU** [comment]
Oh, looks like my tester was on an old version. My bad
