### ISSUE TITLE
Investigating 1.12.2 Fun Ores

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/FunOres#49]
All the information you need
https://paste.dimdev.org/dibeyixuvi.mccrash

**Comment by SilentChaos512** [comment]
What makes you think this is Fun Ores? Crash report indicates ArchitectureCraft (I assume that's what `com.elytradev.architecture` is).

**Comment by P3rf3ctXZer0** [comment]
It only occurs when fun ores is present.

**Comment by P3rf3ctXZer0** [comment]
It has been happening since this version of fun ores. 
FunOres-1.12.2-1.6.0-120.jar

I have been meaning to report this but life has gotten in the way.

Last working release was 

FunOres-universal-1.5.7-118

**Comment by P3rf3ctXZer0** [comment]
I will be investigating it all further today. (PS Borrowing your icon)
![2018-12-21 06_51_55-tessellating block crash on world gen 1 12 2 issue 49 silentchaos512_funore](https://user-images.githubusercontent.com/10351221/50343690-819fbb00-04ed-11e9-9c4a-593e5bceb811.jpg) Just so I know its a testing pack around your mods.

**Comment by P3rf3ctXZer0** [comment]
Okay well somehow it is fine now.

**Comment by P3rf3ctXZer0** [comment]
Using version https://minecraft.curseforge.com/projects/fun-ores/files/2642848 fun ores and silent lib https://minecraft.curseforge.com/projects/silent-lib/files/2650029

**Comment by P3rf3ctXZer0** [comment]
[08:33:16] [Server thread/ERROR] [FML]: Trying to activate the universal filled bucket too late. Call it statically in your Mods class. Mod: Fun Ores

Potentially an issue
