### ISSUE TITLE
Change this mod to act as a "Alloy Smelter/Alloy Creation" API-like mod. And a bit of concerns.

### ISSUE THREAD

**Issue by MagmaSlime123** [SilentChaos512/FunOres#56]
Title says all.

We really don't need 500 random "Mob Ores" or Gears for other mods. We only need the 
ores, ingots, nuggets, and any stuff related to each ore as if it was in the base game.

Let us customize what the mod has in it via enabling/disabling each item on its own 
and having a GUI that lets us define our own recipes in the Alloy Smelter/Metal Furnace.

Due to the current state of the mod, I'm forced to disable a ton of this mod's not-so-useful items (Which aren't even disabling and staying in the Creative menu/JEI as if I never touched it) and not having the ability to create custom recipes. This is the only "Vanilla-like" mod I could find, that adds a way to obtain the common modded alloys in a Vanilla-like block, and I'm not really liking it atm.

Sorry for me blabbing a lot, but I'd really rather prefer a simple 
alloy smeltery mod that doesn't have 99999 other items in it.

**Comment by SilentChaos512** [comment]
Metal ores and the machine blocks no longer exist in the latest version. 1.12.2 is receiving major bug fixes only at this point.

**Comment by MagmaSlime123** [comment]
Well, 1.12/1.14 should act the same or just act as a simple alloy mod, as the issue says.
