### ISSUE TITLE
Smelting Items in Alloy Furnace isnt Working?

### ISSUE THREAD

**Issue by Pandack** [SilentChaos512/FunOres#58]
## Versions

- **Fun Ores**: 1.12.2-1.6.3-124.jar
- **Silent Lib**: 1.12.2-3.0.14+168.jar
- **Forge**: 1.12.2(modded) forge-14.23.5.2854
- **Modpack**: Tinker's Modpack by Emildamgaard(Its in Twitch Minecraft Modpacks)
- **Optifine Installed**: No it is not 

## Expected Behavior

      For the Alloy Smelter to smelt things into items
(Description here)
     I was trying to smelt two coal and one iron into steel with the alloy smelter.
## Actual Behavior

    
(Description here)
     Apparently when I tried making steel with two coal and one iron, it doesn't smelt at all. I have 64 coal as the fuel, and 2 coal+1 iron in the crafting section. That should be able to make steel right? Yet it doesnt sadly.
## Links/Images

- (Link)
https://cdn.discordapp.com/attachments/640540396979748901/778720036885626922/unknown.png
## Steps to Reproduce the Problem

1. Make an alloy smelter
2. Put 64 coal as the fuel
3. Put in 2 coal and one iron into the crafting section
4.  No response.

**Comment by SilentChaos512** [comment]
Sorry, older versions are no longer supported.
