### ISSUE TITLE
Ability to disable un-needed parts

### ISSUE THREAD

**Issue by jriwanek** [SilentChaos512/FunOres#7]
Allow Disabling Blocks, Ingots, Nuggets, Dusts, Plates, Gears, foods & shards independently or globally like you currently do with ores.

**Comment by jriwanek** [comment]
Any progress/thoughts on this one?

**Comment by SilentChaos512** [comment]
What would be disabled, just the recipes to craft the blocks/items?

**Comment by jriwanek** [comment]
I'd suggest recipes, unless you're wanting to work closer with BM, then probably being able to wholey disable things may be a plan. (I'm planning on doing the same with MM and others, can't do much on that front with BM unless Cyano agrees).

**Comment by DRTR0** [comment]
Yes like this.

**Comment by jriwanek** [comment]
Incidentally, I'm assuming your preference would be being able to completely disable modules, not just the recipes?

**Comment by DRTR0** [comment]
I think there should be a config option to enable/disable them which disables/enables them completely, not just the recipe. Like you do with ores, have a global enable/disable gears, plates, etc. at the top, and then a specific list at the bottom. I'm just talking about the gears, plates, hammer, etc. Blocks, ingots, fluids, etc. should be handled by the ore gen config. If say Tin is disabled from ore gen in the config, then nothing of Tin should be loaded in the game.

**Comment by SilentChaos512** [comment]
Since I use metadata blocks/items, removing them entirely would be tricky. But if I remove the recipes and ore dictionary entries and hide the item from JEI and creative tabs, it would be like the item doesn't exist.

**Comment by jriwanek** [comment]
That'd work, not like it costs block or item ids. (:
